---
title: "Comparando mecanismos para jukebox sociais"
output:
    html_document:
    df_print: paged
theme: sandstone
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
theme_set(theme_bw())

library(boot)
library(broom)

knitr::opts_chunk$set(tidy = FALSE,
                      fig.width = 6,
                      fig.height = 5)

```

```{r read}
dados = read_csv(here::here("data/satisfacoes.csv"), 
                 col_types = "cdcc") 

glimpse(dados)
```
```{r}
comparacao2 = dados %>% 
    filter(scenario %in% c("combined", "skip"))

comparacao2 %>%
    slice(1:NROW(comparacao2)) %>% 
    group_by(scenario, user_id) %>% 
    summarise(media = mean(satisfaction), .groups = "drop") %>% 
    group_by(scenario) %>% 
    summarise(media = mean(media), .groups = "drop")
```

```{r}
comparacao2 = dados %>% 
    filter(scenario %in% c("combined", "skip"))

theta2 <- function(d, i) {
    agrupado = d %>% 
        slice(i) %>% 
        group_by(scenario, user_id) %>% 
        summarise(media = mean(satisfaction), .groups = "drop") %>%
        group_by(scenario) %>% 
        summarise(media = mean(media), .groups = "drop")
    b = agrupado %>% filter(scenario == "combined") %>% pull(media)
    l = agrupado %>% filter(scenario == "skip") %>% pull(media)
    l - b
}

theta2(comparacao2, i = 1:NROW(comparacao2))
```

```{r}
comparacao1 = dados %>% 
    filter(scenario %in% c("combined", "skip"))

theta <- function(d, i) {
    agrupado = d %>% 
        slice(i) %>% 
        group_by(scenario) %>% 
        summarise(media = mean(satisfaction))
    b = agrupado %>% filter(scenario == "combined") %>% pull(media)
    l = agrupado %>% filter(scenario == "skip") %>% pull(media)
    l - b
}

theta(comparacao1, i = 1:NROW(comparacao1))
```

```{r}
ci1 = boot(data = comparacao1,
           statistic = theta,
           R = 2000) %>%
    tidy(conf.level = .95,
         conf.method = "bca",
         conf.int = TRUE)

ci1
```

